// <auto-generated />
using BlazorApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp.Migrations
{
    [DbContext(typeof(MainContext))]
    partial class MainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("City")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Region")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = "6e9e0727-62ee-4b48-8cf7-76c1f24bee4c",
                            Address = "Νάουσα",
                            City = "Πάρος",
                            CompanyName = "Epsilon NET",
                            ContactName = "Γιάννης Καλογερόπουλος",
                            Country = "Ελλάδα",
                            Phone = "6947093404",
                            PostalCode = "84401",
                            Region = "Κυκλάδες"
                        },
                        new
                        {
                            Id = "5A6AD17C-A342-4DD6-9A5D-959732DEEA5E",
                            Address = "Στέφανου Σαράφη 12",
                            City = "Χαλάνδρι",
                            CompanyName = "Singular Logic",
                            ContactName = "Μαρία Παπαδοπούλου",
                            Country = "Ελλάδα",
                            Phone = "6945899878",
                            PostalCode = "12345",
                            Region = "Αττική"
                        },
                        new
                        {
                            Id = "D270A06D-6E5D-4845-9F8E-85FABEAA46C5",
                            Address = "Green Hill 2312",
                            City = "California",
                            CompanyName = "Data Communications",
                            ContactName = "Antonia Damascus",
                            Country = "USA",
                            Phone = "(5) 555-3932",
                            PostalCode = "05023"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
